name: BrutalLegendsPlugin
version: '1.0-SNAPSHOT'
author: [ARJ]
main: org.arj.mcplugins.brutallegendsplugin.BrutalLegendsPlugin
api-version: '1.20'

commands:
  toggletotemdrops:
    description: Toogle On/Off Totem Drop Plugin
    usage: /toggletotemdrops
  togglechat:
    description: Toogle On/Off Disable Chat Plugin
    usage: /togglechat
  clearlag:
    description: Clear Lag
    usage: /clearlag